### ISSUE TITLE
pyopencl._cl.RuntimeError: clEnqueueReadBuffer failed: OUT_OF_RESOURCES

### ISSUE THREAD

**Issue by karpe29** [axeldavy/vnlnet#5]
I am get the following Error

> Traceback (most recent call last):
>   File "test.py", line 265, in <module>
>     test(training_args, model_state_dict, video, foutnames, only_frame, cuda, args.add_noise)
>   File "test.py", line 180, in test
>     nearest_neighbors_indices = ps.compute(video_search_extract_gray, training_args.past_frames)
>   File "C:\Users\Sagar\PycharmProjects\noisereduction1\vnlnet\video_patch_search.py", line 137, in compute
>     cl.enqueue_copy(self.queue, dst_pos, dst_pos_cl)
>   File "C:\Users\Sagar\PycharmProjects\noisereduction1\venv\lib\site-packages\pyopencl\__init__.py", line 1719, in enqueue_copy
>     return _cl._enqueue_read_buffer(queue, src, dest, **kwargs)
> pyopencl._cl.RuntimeError: clEnqueueReadBuffer failed: OUT_OF_RESOURCES

OS: Windows 10
Processor: AMD Ryzen 5 1600 Six Core 3.20 GHz
Ram: 16GB
Graphics Card: NVIDIA GT 710 10GB

I have tried running it with & without --cpu, I get same error.

**Comment by yifanlu0227** [comment]
I encountered the same problem, did you solve it?

**Comment by yifanlu0227** [comment]
I got it. I should download and run on the <Nvidia.Cuda Platform>
